# Generated by Django 4.1.5 on 2023-01-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chapter_title_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FilePathField(path='D:\\Projects\\education\\static/img'),
        ),
    ]
